name: Production Branch Workflow

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prod job
        run: echo "Running production branch tasks"
