name: Spec-Kit Validation
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read

jobs:
  validate-specs:
    name: Validate Specification Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check required files exist
        run: |
          echo "Checking for required Spec-Kit files..."
          required_files=(
            ".specify/constitution.md"
            ".specify/spec.md"
            ".specify/plan.md"
            ".specify/tasks"
          )
          missing_files=()
          for file in "${required_files[@]}"; do
            if [ ! -e "$file" ]; then
              missing_files+=("$file")
            fi
          done
          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "❌ Missing required files:"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          fi
          echo "✅ All required files exist"
      - name: Validate Markdown syntax
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: .github/markdown-link-check-config.json
      - name: List tasks
        run: |
          echo "Listing Spec-Kit tasks..."
          if [ -d ".specify/tasks" ]; then
            find .specify/tasks -type f -name "*.md"
          else
            echo "No tasks directory found."
          fi
      - name: Summary
        run: |
          echo "✅ Specification files are valid and tasks are listed."
